name: Accuracy KPIs measurement
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |

          # Write your CML report
          echo "## Main KPIs values comparison" > report.md
          echo "" >> report.md
          #cat .\\reports\\model_comparison.txt >> report.md
          pwd >> report.md
          ls >> report.md
          cml-send-comment report.md
